name: Generate GitHub Snake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  github-snake:
    runs-on: ubuntu-24.04  # Asegúrate de que usas la versión actual de Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload GitHub Snake Images
        uses: actions/upload-artifact@v3  # Asegúrate de que esté usando la versión v3
        with:
          name: github-snake
          path: dist/
