name: Generate GitHub Snake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  github-snake:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#32CD32,#228B22,#006400,#00FF00,#808080&bg_color=333333
      - name: Upload GitHub Snake Images
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: dist/
